# Generated by Django 5.1 on 2025-10-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
